// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/home/HomeArtWorkAditionnal copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeArtWork: typeof import('./src/components/home/HomeArtWork.vue')['default']
    HomeArtWorkAditionnal: typeof import('./src/components/home/HomeArtWorkAditionnal.vue')['default']
    HomeArtWorkCard: typeof import('./src/components/home/HomeArtWorkCard.vue')['default']
    HomeArtWorkMore: typeof import('./src/components/home/HomeArtWorkMore.vue')['default']
    HomeFooter: typeof import('./src/components/home/HomeFooter.vue')['default']
    HomeGrid: typeof import('./src/components/home/HomeGrid.vue')['default']
    HomeHeader: typeof import('./src/components/home/HomeHeader.vue')['default']
    HomeQuote: typeof import('./src/components/home/HomeQuote.vue')['default']
    HomeTopBar: typeof import('./src/components/home/HomeTopBar.vue')['default']
    Navbar: typeof import('./src/components/navbar/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiInput: typeof import('./src/components/ui/UiInput.vue')['default']
    UiLevel: typeof import('./src/components/ui/UiLevel.vue')['default']
    UiLoader: typeof import('./src/components/ui/UiLoader.vue')['default']
    UiPage: typeof import('./src/components/ui/UiPage.vue')['default']
    UiProfilePicture: typeof import('./src/components/ui/UiProfilePicture.vue')['default']
    UiTitle: typeof import('./src/components/ui/UiTitle.vue')['default']
    UiWrapper: typeof import('./src/components/ui/UiWrapper.vue')['default']
  }
}
